a2lix_translation_form:
  locale_provider: default
  locales: '%locale_list%'
  default_locale: '%kernel.default_locale%'
  required_locales: '%kernel.default_locale%'
  templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"
