security:
    encoders:
        FOS\UserBundle\Model\UserInterface: auto

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_USER:   [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                success_handler: security.authentication.success_handler
                failure_handler: security.authentication.failure_handler
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /admin/index
                always_use_default_target_path: false
                target_path_parameter:          _target_path
                use_referer:                    true
                login_path: fos_user_security_login
                check_path: fos_user_security_check

            remember_me:
                secret: "%secret%"
                lifetime: 604800 # 1 week in seconds
                path: /
                domain: ~ # Defaults to the current do
                remember_me_parameter: _remember_me

            logout:
                path: /logout
                invalidate_session: true
                success_handler: authentication.handler.logout_success_handler
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: [ROLE_ADMIN] }
