fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

login:
    path: /login

logout:
    path: /logout
    options: { i18n: false }

register:
    path: /register

app_service:
    resource: '../src/Service/'
    type:     annotation

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   '%translations_path%'
